# Generated by Django 5.1.7 on 2025-03-23 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseCode', models.CharField(max_length=50, unique=True)),
                ('CourseName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=254, unique=True)),
                ('UserInstitute', models.CharField(max_length=255)),
                ('UserRole', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('QuizID', models.AutoField(primary_key=True, serialize=False)),
                ('QuizTitle', models.CharField(max_length=255)),
                ('TimeLimit', models.PositiveIntegerField()),
                ('NumOfQues', models.PositiveIntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='store.course')),
                ('Faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuesID', models.AutoField(primary_key=True, serialize=False)),
                ('QuesText', models.TextField()),
                ('Option1', models.CharField(max_length=255)),
                ('Option2', models.CharField(max_length=255)),
                ('Option3', models.CharField(max_length=255)),
                ('Option4', models.CharField(max_length=255)),
                ('CorrectAns', models.PositiveSmallIntegerField()),
                ('DifficultyLevel', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6)),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='store.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='store.user'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('ScoreID', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.PositiveIntegerField()),
                ('SubmittedAt', models.DateTimeField(auto_now_add=True)),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='store.quiz')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='store.user')),
            ],
            options={
                'unique_together': {('Student', 'Quiz')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('ResID', models.AutoField(primary_key=True, serialize=False)),
                ('Mark', models.PositiveIntegerField()),
                ('SubmittedAt', models.DateTimeField(auto_now_add=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='store.question')),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='store.quiz')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='store.user')),
            ],
            options={
                'unique_together': {('Student', 'Question')},
            },
        ),
    ]
