# Generated by Django 5.1.7 on 2025-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_is_staff_alter_user_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Faculty_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
