# Generated by Django 5.1.7 on 2025-04-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_quiz_faculty_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
